version: "3"

services:
  proxy:
    image: nginx:1.17.6-alpine
    container_name: proxy
    restart: on-failure:5
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - node-network
  web:
    build:
      context: "."
    container_name: "web"
    command: npm run start
    ports: 
      - 3000:3000
    volumes:
      - ./src:/usr/src/app/src
    tty: true
    entrypoint: dockerize -wait tcp://db:3306 --timeout 20s docker-entrypoint.sh
    depends_on:
      - db
    networks:
      - node-network
  db:
    build: 
      context: './.docker/mysql'
      dockerfile: 'Dockerfile'
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports: 
      - 3306:3306
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=docker
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
